/* eslint-disable */
module.exports = {
  someSidebar: {
    ['JavaScript']: [
      // 'javascript00',
      
      'javascript01',
      'javascript02',
      'javascript03',
      'javascript04',
      'javascript05',
      'javascript06',
      'javascript07',
      'javascript08',
      'javascript09',
      'javascript10',
      'javascript11',
      'javascript12',
      'javascript13',
      'javascript14',
      'javascript15',
      'javascript16',
      'javascript17',
      'javascript18',
      'javascript19',
      'javascript20',
      'javascript21',
      'javascript22',
      'javascript23',
      'javascript24',
      'javascript25',
      'javascript26',
      'javascript27',
      'javascript28',
      'javascript29',
      'javascript30',
      'javascript01-1'
    ],
    ['Neurobots']: [
      'neurobots/neurobot01',
      'neurobots/neurobot02',
      'neurobots/neurobot03',
      'neurobots/neurobot04',
      'neurobots/neurobot05',
      'neurobots/neurobot06',
      'neurobots/neurobot07',
      'neurobots/neurobot08'
    ],
    ['React Native']: [
      'reactnative00',
      'reactnative01',
      'reactnative02',
      'reactnative03',
      'reactnative04',
      'reactnative05',
      'reactnative06',
      'reactnative07',
      'reactnative08',
      'reactnative09',
      'reactnative10',
      'reactnative11',
      'reactnative12',
      'reactnative13',
      'reactnative14',
      'reactnative15',
      'reactnative16',
      'reactnative17',
      'reactnative18',
      'reactnative19',
      'reactnative20',
      'reactnative21',
      'reactnative22',
      {
        type: 'category',
        label: 'React Navigation',
        items: ['react-navigation/reactnative00', 'react-navigation/reactnative01', 'react-navigation/reactnative02',  'react-navigation/reactnative03', 'react-navigation/reactnative04', 'react-navigation/reactnative05', 'react-navigation/reactnative06',  'react-navigation/reactnative07', 'react-navigation/reactnative08'],
      },
      {
        type: 'category',
        label: 'MobX',
        items: ['state-management/reactnativestate00'],
      },
      {
        type: 'category',
        label: 'Redux',
        items: ['redux-00', 'redux-01', 'redux-02', 'redux-03', 'redux-04'],
      }, 
    ],
    ['TypeScript']: [
      'typescript00',
      'typescript01',
      'typescript02',
      'typescript03',
      'typescript04',
      'typescript05',
      'typescript06',
      'typescript07',
      'typescript08',
      'typescript09',
      'typescript10'
    ],
    ['UI Kit']: ['unicorn00', 'unicorn01', 'unicorn02'],
    ['Authentication']: ['auth1-00', 'auth1-01', 'auth1-02'],
    ['Web3']: ['web3-00'],
    ['AWS Amplify']: ['amplify-00', 'amplify-01', 'amplify-02', 'amplify-03', 'amplify-04', 'notif-00', 'amplify-05', 'amplify-06'],
    ['Telegraf']: [
      'telegraf/telegraf00'
    ],
    ['Using ChatGPT']: ['chatgpt00', 'chatgpt01'],
    ['Blogging']: ['blogging-01', 'blogging-02', 'blogging-03'],
    ['Rubik\'s Cube']: ['cube-00'],
    ['Scratch']: ['scratch-00', 'scratch-01'],
    ['Startup']: ['startup00', 'startup01', 'startup02'],
    ['Interview']: ['interview/interview00', 'interview/interview01', 'interview/interview02'],
    ['Make.com']: ['make/make01', 'make/make02']
  }
}
